name: Mac

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-macos:
    runs-on: macos-latest

    defaults:
      run:
        shell: bash

    env:
      GIT_COMMIT: ${{ github.sha }}

    steps:
    - uses: actions/checkout@v2

    - name: Install brew dependencies
      run: |
        brew list qt5 &>/dev/null || brew install qt5
        brew list openssl &>/dev/null || brew install openssl

    - name: Build
      run: |
        mkdir build
        cd build
        cmake \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=10.14 \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_PREFIX_PATH="$(brew --prefix qt5);$(brew --prefix openssl)" ..
        . ./version
        make -j
    
    # Uncomment to get SSH access for testing
    #- name: Setup tmate session
    #  if: always()
    #  uses: mxschmitt/action-tmate@v3
    
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: ./build/bin/

    - name: Run unit test
      run: ./build/bin/unittests
